db:
  db_name: {{setup.rekuest.db_name}}
  engine: django.db.backends.postgresql
  host: db
  password: {{setup.postgres_password}}
  port: 5432
  username: {{setup.postgres_user}}
django:
  admin:
    password: {{setup.admin_password}}
    username: {{setup.admin_username}}
  debug: false
  hosts:
  - '*'
  secret_key: {{setup.rekuest.django_secret_key}}
lok:
  issuer: lok
  key_type: RS256
  public_key: {{setup.jwt_key_pair.public_key}}{% if setup.static_tokens %}
  static_tokens: {% for token, user in setup.static_tokens.items() %}
    {{token}}: 
      sub: {{user.sub}}{% endfor %}{% endif %}
minio:
  access_key: {{setup.rekuest.bucket.access_key}}
  buckets:
   media: rekuestmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: {{setup.rekuest.bucket.secret_key}}
redis:
  host: redis
  port: 6379
rabbitmq:
  host: rabbitmq
  password: guest
  port: 5672
  username: guest
  v_host: ''
