projects:
  arkitekt:
    schema: http://localhost:8090/graphql
    documents: graphql/*/**.graphql
    extensions:
      turms:
        out_dir: arkitekt/api
        freeze: True
        always_resolve_interfaces: True
        parsers:
          - type: turms.parsers.polyfill.PolyfillParser
            python_version: 3.7
        stylers:
          - type: turms.stylers.default.DefaultStyler
          - type: turms.stylers.appender.AppenderStyler
            append_fragment: "Fragment"
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - type: arkitekt.rath.ArkitektRath
                key: rath
                description: "The arkitekt rath client"
            definitions:
              - type: subscription
                is_async: True
                use: arkitekt.funcs.asubscribe
              - type: query
                is_async: True
                use: arkitekt.funcs.aexecute
              - type: mutation
                is_async: True
                use: arkitekt.funcs.aexecute
              - type: subscription
                use: arkitekt.funcs.subscribe
              - type: query
                use: arkitekt.funcs.execute
              - type: mutation
                use: arkitekt.funcs.execute
        processors:
          - type: turms.processors.black.BlackProcessor
        scalar_definitions:
          uuid: str
          Callback: str
          Any: typing.Any
          QString: arkitekt.scalars.QString
        additional_bases:
          Node:
            - arkitekt.traits.node.Reserve
          IntArgPort:
            - arkitekt.traits.ports.IntExpander
          IntKwargPort:
            - arkitekt.traits.ports.IntExpander
          IntReturnPort:
            - arkitekt.traits.ports.IntExpander
          StructureArgPort:
            - arkitekt.traits.ports.StructureExpander
          StructureKwargPort:
            - arkitekt.traits.ports.StructureExpander
          StructureReturnPort:
            - arkitekt.traits.ports.StructureExpander
          ListArgPort:
            - arkitekt.traits.ports.ListExpander
          ListKwargPort:
            - arkitekt.traits.ports.ListExpander
          ListReturnPort:
            - arkitekt.traits.ports.ListExpander
          DictArgPort:
            - arkitekt.traits.ports.DictExpander
          DictKwargPort:
            - arkitekt.traits.ports.DictExpander
          DictReturnPort:
            - arkitekt.traits.ports.DictExpander
          BoolArgPort:
            - arkitekt.traits.ports.BoolExpander
          BoolKwargPort:
            - arkitekt.traits.ports.BoolExpander
          BoolReturnPort:
            - arkitekt.traits.ports.BoolExpander
          StringArgPort:
            - arkitekt.traits.ports.StringExpander
          StringKwargPort:
            - arkitekt.traits.ports.StringExpander
          StringReturnPort:
            - arkitekt.traits.ports.StringExpander
          EnumArgPort:
            - arkitekt.traits.ports.EnumExpander
          EnumKwargPort:
            - arkitekt.traits.ports.EnumExpander
          EnumReturnPort:
            - arkitekt.traits.ports.EnumExpander
