schema: http://localhost:8070/graphql
documents: graphql/fluss/*/**.graphql
extensions:
  turms:
    out_dir: fluss/api
    exclude_typenames: true
    freeze:
      enabled: true
    options:
      enabled: true
      use_enum_values: true
      extra: "forbid"
      types:
        - "input"
    stylers:
      - type: turms.stylers.default.DefaultStyler
      - type: turms.stylers.appender.AppenderStyler
        append_fragment: "Fragment"
    plugins:
      - type: turms.plugins.enums.EnumsPlugin
        skip_unreferenced: True
      - type: turms.plugins.inputs.InputsPlugin
        skip_unreferenced: True
      - type: turms.plugins.fragments.FragmentsPlugin
      - type: turms.plugins.operations.OperationsPlugin
      - type: turms.plugins.funcs.FuncsPlugin
        global_kwargs:
          - type: fluss.rath.FlussRath
            key: rath
            description: "The client we want to use (defaults to the currently active client)"
        definitions:
          - type: subscription
            is_async: True
            use: fluss.funcs.asubscribe
          - type: query
            is_async: True
            use: fluss.funcs.aexecute
          - type: mutation
            is_async: True
            use: fluss.funcs.aexecute
          - type: subscription
            use: fluss.funcs.subscribe
          - type: query
            use: fluss.funcs.execute
          - type: mutation
            use: fluss.funcs.execute
    processors:
      - type: turms.processors.black.BlackProcessor
    scalar_definitions:
      uuid: str
      Callback: str
      Any: typing.Any
      ID: rath.scalars.ID
      EventValue: fluss.scalars.EventValue
    additional_config:
      EdgeInput:
        allow_population_by_field_name: True
    additional_bases:
      FlowGraph:
        - fluss.traits.Graph
      StreamItem:
        - fluss.traits.MockableTrait
      StreamItemChild:
        - fluss.traits.MockableTrait
