activation_days: 7
apps:
- client_id: soinfosienfoaswdasdasdisnefoisneofinsef
  client_secret: soinfosiengeesegegfoisnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikromanager
  name: MikroManager
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
- client_id: soinfosienfoisnseghsggegefoisneofinsef
  client_secret: soinfosienesfseffoisnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikroj
  name: MikroJ
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
- client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
  client_secret: soinfosienfoissdfsdfnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikro-napari
  name: napari
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
db:
  db_name: lok_db
  engine: django.db.backends.postgresql
  host: db
  password: ed739bc1772e1c012374f07908bf6577
  port: 5432
  username: pokeyceladonant
deployment:
  name: defaults
django:
  admin:
    email: asd@soaidna.de
    password: sdfsef
    username: asdasd
  debug: false
  hosts:
  - '*'
  secret_key: vu1--7shxqz)k4p=xxa^hbv6@)o!pq4e7&ema%abhzyqom$42x
groups:
- description: My Perfect Team
  name: myteam
minio:
  access_key: smellycopperfalcon
  buckets:
  - name: lokmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: b7713859396508b677cc189990cf9673
private_key: '-----BEGIN PRIVATE KEY-----

  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgQ4wDZaLBBioN

  RExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HP

  I0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox

  /M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN

  7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetK

  dkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2

  aG+h4K1lAgMBAAECggEAHlk8OeZ0wB3FN9bvqC0LTaplaTEzKrT3JKUX9mlhrhgk

  +E4cWoo1srd+vR9nxSEtEEGIw/fkBKBOhR21oWryw9KJDKARVsLkqbDwyaZBbu+A

  G/F3EMqEu6H468UWb6EIr+b6WNbtt1Vg0+9+Bn+6HqHjcJTOw5F7ZPnJWh9xKFLa

  G3pMyVkq0/NOrN5txc5JXOKPYqvjjTk5i0zk//ONhoYuraUJM8yzJYTjd0PHtYgs

  KreYyKc5J98iCa3AEzzu/zNseAwa1DchM0MyvUiRbNluB0qD+HenouzPyKxrghmu

  Nk3cWnBMijI7D6vEbye/H541FBWXPseua2V+6LayDwKBgQDJX7+U+0gsrQmMNKDw

  HMkrFGGhMBNtb4sR47JbJDrwqlwRxyellBtRJ7zRjw6iAk2mpSc8WzfxsQk8DqM6

  ZsjJ/GBoyZ5ICawVDF6ato79Gny6hzx0KxS/OpIsd6pRzaLjiLmje1TfGyB4FLhh

  oiLs0d6r4OVhVqKZNfXybMdnRwKBgQDLvO/9NLxKaT/nVthRmc7V8RDpJODy627n

  RufnzJ9QCPs7tvd/YhgnefirADZ9xu1hRY2JQjadAVln71AFgBENR8P3f8w7maE6

  ftBgIPDIPEL+qK/S2ZM5HYUP7X8v3h7ppInYX3SsXqj/X1ko7kkFyesCMbeTpVAf

  yJl4GQWz8wKBgARgIDmMfDT8TYjOW/Dbr0NQXg6yjLmEAvGQkP+J+f3gtb9tJF9k

  qHNK+b9T7G14v1cvn3qgQMbvodO8Pa+3LAW3hiDAwL+v9h0+949FCDZXrP4gkh+0

  D+9XxnVQ5FKCtVdcUSxMMbvnSv1Q9fCpJTkgFkaFzHYg+8d4dK+fzXVhAoGBAJiP

  05nkynZiF+Mwqe144mRcDtC2t+fPmo1/EBsIo+d3wkF2AiEWIIY3FJlgIG3Q72Ke

  hZzZwzGQmBV3I5Hq01oBemI0BYg/w3adDYZeRE98qKIvSPH30QG89C34Jvx+NOG6

  PyqSWDjW7W/FQ2ud+3plOCC9f/0EllomiZ1gB2A3AoGAV2bj3IFJybOTtRlqF3eI

  sKgBG5UO+Cs6+MyyXFPQo54Sg5mdhxKaAKTB0meWlyTMczA/o5C+ZcwKRR7tI9c/

  6TRmuKoyW7C6XsnoyeIELzuQjrhGCTwnO3sl3U7l3sp2Bt2exzVxU9uj80cI9knm

  l2hr8PzE2jOOOjWzv3HT4Eg=

  -----END PRIVATE KEY-----

  '
public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
redis:
  host: redis
  port: 6379
scopes:
  can_assign: Can Assign Nodes
  can_create: Can Create Nodes
  can_create_identifier: Can create new identifier for the platform
  can_forward_bounce: Can reserve and assign to Nodes mimicking other Users (only
    backend and admin)
  can_provide: Can Provide Nodes
  can_template: Can Template Nodes
  introspection: Introspect the Token scope
  provider: Can act as a provider
  read: Reading all of your Data
  read_starred: Reading all of your shared Data
token_expire_seconds: 604800
users:
- email: sdfsd@gmail.com
  groups:
  - myteam
  password: sdf
  username: sdf
