db:
  db_name: mikro_db
  engine: django.db.backends.postgresql
  host: db
  password: ed739bc1772e1c012374f07908bf6577
  port: 5432
  username: pokeyceladonant
django:
  admin:
    email: asd@soaidna.de
    password: sdfsef
    username: asdasd
  debug: false
  hosts:
  - '*'
  secret_key: og0a-m*m34n1uhwe)_l^(3&qlfyu-zkq+q+i7qn3u^(_ssv@8=
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
minio:
  access_key: squeakydandelioncaracal
  buckets:
  - name: zarr
  - name: parquet
  - name: mikromedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 42de3d260cda01823e1564a0ea68b92d
redis:
  host: redis
  port: 6379
