buckets:
- name: lokmedia
- name: lokmedia
- name: zarr
- name: parquet
- name: mikromedia
- name: lokmedia
- name: flussmedia
- name: lokmedia
users:
- access_key: bumpycopperdonkey
  name: lok
  policies:
  - readwrite
  secret_key: dd3c74d7f8cb6a8ed08d4d1ce5806288
- access_key: whinyindigoharrier
  name: lok
  policies:
  - readwrite
  secret_key: d960cb808790dc1e34447105d2f869ca
- access_key: squeakydandelioncaracal
  name: mikro
  policies:
  - readwrite
  secret_key: 42de3d260cda01823e1564a0ea68b92d
- access_key: paltryceladonolm
  name: lok
  policies:
  - readwrite
  secret_key: 756eb41cb0509abaa092f165f16b0a9c
- access_key: chummygreylemur
  name: fluss
  policies:
  - readwrite
  secret_key: d6b8098acb5a40c1a8cc30533e68fcac
- access_key: smellycopperfalcon
  name: lok
  policies:
  - readwrite
  secret_key: b7713859396508b677cc189990cf9673
