db:
  db_name: port_db
  engine: django.db.backends.postgresql
  host: db
  password: ed739bc1772e1c012374f07908bf6577
  port: 5432
  username: pokeyceladonant
django:
  admin:
    email: asd@soaidna.de
    password: sdfsef
    username: asdasd
  debug: false
  hosts:
  - '*'
  secret_key: '&-qrdrvywi#_q)xjx=0c2s$u6dem)lk$@3_guk#iqxo&w_v@b-'
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
redis:
  host: redis
  port: 6379
virtualizer:
  allowed_runtimes:
  - nvidia
  - runc
  - wasm
  engine: docker
  network: dev
