schema: http://localhost:8080/graphql
documents: graphql/mikro/*/**.graphql
extensions:
  turms:
    out_dir: mikro/api
    exclude_typenames: true
    freeze:
      enabled: true
    options:
      enabled: true
      use_enum_values: true
      extra: "forbid"
      types:
        - "input"
    stylers:
      - type: turms.stylers.default.DefaultStyler
      - type: turms.stylers.appender.AppenderStyler
        append_fragment: "Fragment"
    plugins:
      - type: turms.plugins.enums.EnumsPlugin
        skip_unreferenced: True
      - type: turms.plugins.inputs.InputsPlugin
        skip_unreferenced: True
      - type: turms.plugins.fragments.FragmentsPlugin
      - type: turms.plugins.operations.OperationsPlugin

      - type: turms.plugins.funcs.FuncsPlugin
        global_kwargs:
          - type: mikro.rath.MikroRath
            key: rath
            description: "The mikro rath client"
        definitions:
          - type: subscription
            is_async: True
            use: mikro.funcs.asubscribe
          - type: query
            is_async: True
            use: mikro.funcs.aexecute
          - type: mutation
            is_async: True
            use: mikro.funcs.aexecute
          - type: subscription
            use: mikro.funcs.subscribe
          - type: query
            use: mikro.funcs.execute
          - type: mutation
            use: mikro.funcs.execute
    processors:
      - type: turms.processors.black.BlackProcessor
    scalar_definitions:
      XArrayInput: mikro.scalars.XArrayInput
      BigFile: mikro.scalars.BigFile
      File: mikro.scalars.File
      ImageFile: mikro.scalars.File
      Upload: mikro.scalars.Upload
      ModelData: mikro.scalars.ModelData
      ModelFile: mikro.scalars.ModelFile
      ParquetInput: mikro.scalars.ParquetInput
      Store: mikro.scalars.Store
      Parquet: mikro.scalars.Parquet
      ID: rath.scalars.ID
      AffineMatrix: mikro.scalars.AffineMatrix
      MetricValue: mikro.scalars.MetricValue
      AssignationID: mikro.scalars.AssignationID
      FeatureValue: mikro.scalars.FeatureValue
    additional_bases:
      Representation:
        - mikro.traits.Representation
      Table:
        - mikro.traits.Table
      Omero:
        - mikro.traits.Omero
      Objective:
        - mikro.traits.Objective
      Position:
        - mikro.traits.Position
      Stage:
        - mikro.traits.Stage
      ROI:
        - mikro.traits.ROI
      InputVector:
        - mikro.traits.Vectorizable
      PhysicalSize:
        - mikro.traits.PhysicalSize
