admin_email: asd@soaidna.de
admin_password: sdfsef
admin_username: asdasd
apps:
- client_id: soinfosienfoaswdasdasdisnefoisneofinsef
  client_secret: soinfosiengeesegegfoisnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikromanager
  name: MikroManager
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
- client_id: soinfosienfoisnseghsggegefoisneofinsef
  client_secret: soinfosienesfseffoisnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikroj
  name: MikroJ
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
- client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
  client_secret: soinfosienfoissdfsdfnefoisneofinsef
  client_type: public
  grant_type: authorization-code
  identifier: github.io.jhnnsrs.mikro-napari
  name: napari
  redirect_uris:
  - http://localhost:8090
  scopes:
  - read
  - write
  tenant: sdf
  version: latest
bindings:
- host: 172.22.0.1
  ip: null
  name: br-f51969b2cbe1-ip
  ssl: false
- host: 172.18.0.1
  ip: null
  name: br-b03a77cbc214-ip
  ssl: false
- host: 100.91.169.37
  ip: null
  name: tailscale0-ip
  ssl: false
- host: 10.144.196.141
  ip: null
  name: enp3s0-ip
  ssl: false
- host: 172.19.0.1
  ip: null
  name: br-76f3efef6d41-ip
  ssl: false
- host: 172.21.0.1
  ip: null
  name: br-4f0dd4fdbcf5-ip
  ssl: false
- host: 172.17.0.1
  ip: null
  name: docker0-ip
  ssl: false
- host: jhnnsrs-server
  ip: null
  name: br-e7c145396c6b
  ssl: false
- host: jhnnsrs-server.jhnnsrs.gmail.com.beta.tailscale.net
  ip: null
  name: tailscale0
  ssl: false
- host: 172.23.0.1
  ip: null
  name: br-8047b438ec7a-ip
  ssl: false
- host: 127.0.0.1
  ip: null
  name: lo-ip
  ssl: false
- host: 192.168.49.1
  ip: null
  name: br-e7c145396c6b-ip
  ssl: false
- host: 172.20.0.1
  ip: null
  name: br-d8f95bbc5a2c-ip
  ssl: false
- host: localhost
  ip: null
  name: lo
  ssl: false
- host: 172.27.0.1
  ip: null
  name: br-4a492c68c219-ip
  ssl: false
fakts_port: 8000
groups:
- description: My Perfect Team
  name: myteam
name: defaults
services:
- dependencies: {}
  description: The hub
  dev: null
  docker_network_name: hub
  image: jhnnsrs/hub:prod
  interface: hub
  long: Access this compuer resources from anywhere in nice juypter notebooks
  name: hub
  port: 8040
  public_port: 8040
  requires:
  - lok
- activation_days: 7
  dependencies: {}
  description: The core
  dev: null
  host: lok
  image: jhnnsrs/lok:prod
  interface: lok
  issuer: lok
  key_type: RS256
  long: This includes authorization, authentificaiton, config management, and more
  name: lok
  port: 8000
  private_key: '-----BEGIN PRIVATE KEY-----

    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgQ4wDZaLBBioN

    RExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HP

    I0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox

    /M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN

    7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetK

    dkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2

    aG+h4K1lAgMBAAECggEAHlk8OeZ0wB3FN9bvqC0LTaplaTEzKrT3JKUX9mlhrhgk

    +E4cWoo1srd+vR9nxSEtEEGIw/fkBKBOhR21oWryw9KJDKARVsLkqbDwyaZBbu+A

    G/F3EMqEu6H468UWb6EIr+b6WNbtt1Vg0+9+Bn+6HqHjcJTOw5F7ZPnJWh9xKFLa

    G3pMyVkq0/NOrN5txc5JXOKPYqvjjTk5i0zk//ONhoYuraUJM8yzJYTjd0PHtYgs

    KreYyKc5J98iCa3AEzzu/zNseAwa1DchM0MyvUiRbNluB0qD+HenouzPyKxrghmu

    Nk3cWnBMijI7D6vEbye/H541FBWXPseua2V+6LayDwKBgQDJX7+U+0gsrQmMNKDw

    HMkrFGGhMBNtb4sR47JbJDrwqlwRxyellBtRJ7zRjw6iAk2mpSc8WzfxsQk8DqM6

    ZsjJ/GBoyZ5ICawVDF6ato79Gny6hzx0KxS/OpIsd6pRzaLjiLmje1TfGyB4FLhh

    oiLs0d6r4OVhVqKZNfXybMdnRwKBgQDLvO/9NLxKaT/nVthRmc7V8RDpJODy627n

    RufnzJ9QCPs7tvd/YhgnefirADZ9xu1hRY2JQjadAVln71AFgBENR8P3f8w7maE6

    ftBgIPDIPEL+qK/S2ZM5HYUP7X8v3h7ppInYX3SsXqj/X1ko7kkFyesCMbeTpVAf

    yJl4GQWz8wKBgARgIDmMfDT8TYjOW/Dbr0NQXg6yjLmEAvGQkP+J+f3gtb9tJF9k

    qHNK+b9T7G14v1cvn3qgQMbvodO8Pa+3LAW3hiDAwL+v9h0+949FCDZXrP4gkh+0

    D+9XxnVQ5FKCtVdcUSxMMbvnSv1Q9fCpJTkgFkaFzHYg+8d4dK+fzXVhAoGBAJiP

    05nkynZiF+Mwqe144mRcDtC2t+fPmo1/EBsIo+d3wkF2AiEWIIY3FJlgIG3Q72Ke

    hZzZwzGQmBV3I5Hq01oBemI0BYg/w3adDYZeRE98qKIvSPH30QG89C34Jvx+NOG6

    PyqSWDjW7W/FQ2ud+3plOCC9f/0EllomiZ1gB2A3AoGAV2bj3IFJybOTtRlqF3eI

    sKgBG5UO+Cs6+MyyXFPQo54Sg5mdhxKaAKTB0meWlyTMczA/o5C+ZcwKRR7tI9c/

    6TRmuKoyW7C6XsnoyeIELzuQjrhGCTwnO3sl3U7l3sp2Bt2exzVxU9uj80cI9knm

    l2hr8PzE2jOOOjWzv3HT4Eg=

    -----END PRIVATE KEY-----

    '
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
  public_port: 8000
  required_buckets:
  - name: lokmedia
  required_policies:
  - readwrite
  requires:
  - redis
  - db
  - minio
  scopes:
    can_assign: Can Assign Nodes
    can_create: Can Create Nodes
    can_create_identifier: Can create new identifier for the platform
    can_forward_bounce: Can reserve and assign to Nodes mimicking other Users (only
      backend and admin)
    can_provide: Can Provide Nodes
    can_template: Can Template Nodes
    introspection: Introspect the Token scope
    provider: Can act as a provider
    read: Reading all of your Data
    read_starred: Reading all of your shared Data
  token_expire_seconds: 604800
- dependencies: {}
  description: The virtualizer
  dev: null
  host: port
  image: jhnnsrs/port:prod
  interface: port
  long: Enables one click install of github repos as internal apps
  name: port
  port: 8050
  public_port: 8050
  requires:
  - redis
  - lok
  - rekuest
  - rabbitmq
  - db
- dependencies: {}
  description: The pubsub
  dev: null
  host: redis
  image: redis:latest
  interface: redis
  long: This allows services to publish and subscribe to events
  name: redis
  port: 6379
  requires: []
- databases: []
  dependencies: {}
  description: The database
  dev: null
  host: db
  image: jhnnsrs/daten:prod
  interface: db
  long: Storing your meta data
  name: postgres
  password: aeaeb757877ceb34fc2ddf728832b5e3
  port: 5432
  requires: []
  username: crankyivoryschnauzer
- dependencies: {}
  description: The backbone
  dev: null
  host: rabbitmq
  image: jhnnsrs/mister:fancy
  interface: rabbitmq
  long: Taking care of the reliable communication between the apps
  name: rabbitmq
  password: guest
  port: 5672
  requires: []
  username: guest
- activation_days: 7
  dependencies: {}
  description: The core
  dev: null
  host: lok
  image: jhnnsrs/lok:prod
  interface: lok
  issuer: lok
  key_type: RS256
  long: This includes authorization, authentificaiton, config management, and more
  name: lok
  port: 8000
  private_key: '-----BEGIN PRIVATE KEY-----

    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgQ4wDZaLBBioN

    RExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HP

    I0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox

    /M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN

    7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetK

    dkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2

    aG+h4K1lAgMBAAECggEAHlk8OeZ0wB3FN9bvqC0LTaplaTEzKrT3JKUX9mlhrhgk

    +E4cWoo1srd+vR9nxSEtEEGIw/fkBKBOhR21oWryw9KJDKARVsLkqbDwyaZBbu+A

    G/F3EMqEu6H468UWb6EIr+b6WNbtt1Vg0+9+Bn+6HqHjcJTOw5F7ZPnJWh9xKFLa

    G3pMyVkq0/NOrN5txc5JXOKPYqvjjTk5i0zk//ONhoYuraUJM8yzJYTjd0PHtYgs

    KreYyKc5J98iCa3AEzzu/zNseAwa1DchM0MyvUiRbNluB0qD+HenouzPyKxrghmu

    Nk3cWnBMijI7D6vEbye/H541FBWXPseua2V+6LayDwKBgQDJX7+U+0gsrQmMNKDw

    HMkrFGGhMBNtb4sR47JbJDrwqlwRxyellBtRJ7zRjw6iAk2mpSc8WzfxsQk8DqM6

    ZsjJ/GBoyZ5ICawVDF6ato79Gny6hzx0KxS/OpIsd6pRzaLjiLmje1TfGyB4FLhh

    oiLs0d6r4OVhVqKZNfXybMdnRwKBgQDLvO/9NLxKaT/nVthRmc7V8RDpJODy627n

    RufnzJ9QCPs7tvd/YhgnefirADZ9xu1hRY2JQjadAVln71AFgBENR8P3f8w7maE6

    ftBgIPDIPEL+qK/S2ZM5HYUP7X8v3h7ppInYX3SsXqj/X1ko7kkFyesCMbeTpVAf

    yJl4GQWz8wKBgARgIDmMfDT8TYjOW/Dbr0NQXg6yjLmEAvGQkP+J+f3gtb9tJF9k

    qHNK+b9T7G14v1cvn3qgQMbvodO8Pa+3LAW3hiDAwL+v9h0+949FCDZXrP4gkh+0

    D+9XxnVQ5FKCtVdcUSxMMbvnSv1Q9fCpJTkgFkaFzHYg+8d4dK+fzXVhAoGBAJiP

    05nkynZiF+Mwqe144mRcDtC2t+fPmo1/EBsIo+d3wkF2AiEWIIY3FJlgIG3Q72Ke

    hZzZwzGQmBV3I5Hq01oBemI0BYg/w3adDYZeRE98qKIvSPH30QG89C34Jvx+NOG6

    PyqSWDjW7W/FQ2ud+3plOCC9f/0EllomiZ1gB2A3AoGAV2bj3IFJybOTtRlqF3eI

    sKgBG5UO+Cs6+MyyXFPQo54Sg5mdhxKaAKTB0meWlyTMczA/o5C+ZcwKRR7tI9c/

    6TRmuKoyW7C6XsnoyeIELzuQjrhGCTwnO3sl3U7l3sp2Bt2exzVxU9uj80cI9knm

    l2hr8PzE2jOOOjWzv3HT4Eg=

    -----END PRIVATE KEY-----

    '
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
  public_port: 8000
  required_buckets:
  - name: lokmedia
  required_policies:
  - readwrite
  requires:
  - redis
  - db
  - minio
  scopes:
    can_assign: Can Assign Nodes
    can_create: Can Create Nodes
    can_create_identifier: Can create new identifier for the platform
    can_forward_bounce: Can reserve and assign to Nodes mimicking other Users (only
      backend and admin)
    can_provide: Can Provide Nodes
    can_template: Can Template Nodes
    introspection: Introspect the Token scope
    provider: Can act as a provider
    read: Reading all of your Data
    read_starred: Reading all of your shared Data
  token_expire_seconds: 604800
- dependencies: {}
  description: The broker
  dev: null
  host: rekuest
  image: jhnnsrs/rekuest:prod
  interface: rekuest
  long: Allows you to call enabled bioimage apps from the platform
  name: rekuest
  port: 8090
  public_port: 8090
  requires:
  - redis
  - rabbitmq
  - lok
  - db
- dependencies: {}
  description: The datalayer
  dev: null
  host: mikro
  image: jhnnsrs/mikro:prod
  interface: mikro
  long: Enables you to store, organize and monitor microscopy data
  name: mikro
  port: 8080
  public_port: 8080
  required_buckets:
  - name: zarr
  - name: parquet
  - name: mikromedia
  required_policies:
  - readwrite
  requires:
  - redis
  - lok
  - db
  - minio
- dependencies: {}
  description: The pubsub
  dev: null
  host: redis
  image: redis:latest
  interface: redis
  long: This allows services to publish and subscribe to events
  name: redis
  port: 6379
  requires: []
- databases: []
  dependencies: {}
  description: The database
  dev: null
  host: db
  image: jhnnsrs/daten:prod
  interface: db
  long: Storing your meta data
  name: postgres
  password: 3880c6c482dc7ff41a158213154f6fae
  port: 5432
  requires: []
  username: hazyflaxschnauzer
- buckets: []
  dashboard_port: 9001
  dependencies: {}
  description: The storage
  dev: null
  host: minio
  image: minio/minio:RELEASE.2023-02-10T18-48-39Z
  init_image: jhnnsrs/init:prod
  interface: minio
  long: Storing your images and files
  name: minio
  port: 9000
  public_dashboard_port: 9001
  public_port: 9000
  requires: []
  root_password: fecd65cacb36a9f01e6aea61e7481da4
  root_username: hastysangriatuatara
  users: []
  with_dashboard: false
- activation_days: 7
  dependencies: {}
  description: The core
  dev: null
  host: lok
  image: jhnnsrs/lok:prod
  interface: lok
  issuer: lok
  key_type: RS256
  long: This includes authorization, authentificaiton, config management, and more
  name: lok
  port: 8000
  private_key: '-----BEGIN PRIVATE KEY-----

    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgQ4wDZaLBBioN

    RExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HP

    I0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox

    /M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN

    7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetK

    dkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2

    aG+h4K1lAgMBAAECggEAHlk8OeZ0wB3FN9bvqC0LTaplaTEzKrT3JKUX9mlhrhgk

    +E4cWoo1srd+vR9nxSEtEEGIw/fkBKBOhR21oWryw9KJDKARVsLkqbDwyaZBbu+A

    G/F3EMqEu6H468UWb6EIr+b6WNbtt1Vg0+9+Bn+6HqHjcJTOw5F7ZPnJWh9xKFLa

    G3pMyVkq0/NOrN5txc5JXOKPYqvjjTk5i0zk//ONhoYuraUJM8yzJYTjd0PHtYgs

    KreYyKc5J98iCa3AEzzu/zNseAwa1DchM0MyvUiRbNluB0qD+HenouzPyKxrghmu

    Nk3cWnBMijI7D6vEbye/H541FBWXPseua2V+6LayDwKBgQDJX7+U+0gsrQmMNKDw

    HMkrFGGhMBNtb4sR47JbJDrwqlwRxyellBtRJ7zRjw6iAk2mpSc8WzfxsQk8DqM6

    ZsjJ/GBoyZ5ICawVDF6ato79Gny6hzx0KxS/OpIsd6pRzaLjiLmje1TfGyB4FLhh

    oiLs0d6r4OVhVqKZNfXybMdnRwKBgQDLvO/9NLxKaT/nVthRmc7V8RDpJODy627n

    RufnzJ9QCPs7tvd/YhgnefirADZ9xu1hRY2JQjadAVln71AFgBENR8P3f8w7maE6

    ftBgIPDIPEL+qK/S2ZM5HYUP7X8v3h7ppInYX3SsXqj/X1ko7kkFyesCMbeTpVAf

    yJl4GQWz8wKBgARgIDmMfDT8TYjOW/Dbr0NQXg6yjLmEAvGQkP+J+f3gtb9tJF9k

    qHNK+b9T7G14v1cvn3qgQMbvodO8Pa+3LAW3hiDAwL+v9h0+949FCDZXrP4gkh+0

    D+9XxnVQ5FKCtVdcUSxMMbvnSv1Q9fCpJTkgFkaFzHYg+8d4dK+fzXVhAoGBAJiP

    05nkynZiF+Mwqe144mRcDtC2t+fPmo1/EBsIo+d3wkF2AiEWIIY3FJlgIG3Q72Ke

    hZzZwzGQmBV3I5Hq01oBemI0BYg/w3adDYZeRE98qKIvSPH30QG89C34Jvx+NOG6

    PyqSWDjW7W/FQ2ud+3plOCC9f/0EllomiZ1gB2A3AoGAV2bj3IFJybOTtRlqF3eI

    sKgBG5UO+Cs6+MyyXFPQo54Sg5mdhxKaAKTB0meWlyTMczA/o5C+ZcwKRR7tI9c/

    6TRmuKoyW7C6XsnoyeIELzuQjrhGCTwnO3sl3U7l3sp2Bt2exzVxU9uj80cI9knm

    l2hr8PzE2jOOOjWzv3HT4Eg=

    -----END PRIVATE KEY-----

    '
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
  public_port: 8000
  required_buckets:
  - name: lokmedia
  required_policies:
  - readwrite
  requires:
  - redis
  - db
  - minio
  scopes:
    can_assign: Can Assign Nodes
    can_create: Can Create Nodes
    can_create_identifier: Can create new identifier for the platform
    can_forward_bounce: Can reserve and assign to Nodes mimicking other Users (only
      backend and admin)
    can_provide: Can Provide Nodes
    can_template: Can Template Nodes
    introspection: Introspect the Token scope
    provider: Can act as a provider
    read: Reading all of your Data
    read_starred: Reading all of your shared Data
  token_expire_seconds: 604800
- dependencies: {}
  description: The designer
  dev: null
  host: fluss
  image: jhnnsrs/fluss:prod
  interface: fluss
  long: Allows you to design universal workflows spanning multiple apps
  name: fluss
  port: 8070
  public_port: 8070
  required_buckets:
  - name: flussmedia
  required_policies:
  - readwrite
  requires:
  - redis
  - lok
  - rekuest
  - rabbitmq
  - db
  - minio
- dependencies: {}
  description: The pubsub
  dev: null
  host: redis
  image: redis:latest
  interface: redis
  long: This allows services to publish and subscribe to events
  name: redis
  port: 6379
  requires: []
- databases: []
  dependencies: {}
  description: The database
  dev: null
  host: db
  image: jhnnsrs/daten:prod
  interface: db
  long: Storing your meta data
  name: postgres
  password: ed739bc1772e1c012374f07908bf6577
  port: 5432
  requires: []
  username: pokeyceladonant
- buckets: []
  dashboard_port: 9001
  dependencies: {}
  description: The storage
  dev: null
  host: minio
  image: minio/minio:RELEASE.2023-02-10T18-48-39Z
  init_image: jhnnsrs/init:prod
  interface: minio
  long: Storing your images and files
  name: minio
  port: 9000
  public_dashboard_port: 9001
  public_port: 9000
  requires: []
  root_password: 6a606b701ca4ec6e7856c3d0cef063bb
  root_username: hastylinenowl
  users: []
  with_dashboard: false
- dependencies: {}
  description: The backbone
  dev: null
  host: rabbitmq
  image: jhnnsrs/mister:fancy
  interface: rabbitmq
  long: Taking care of the reliable communication between the apps
  name: rabbitmq
  password: guest
  port: 5672
  requires: []
  username: guest
- activation_days: 7
  dependencies: {}
  description: The core
  dev: null
  host: lok
  image: jhnnsrs/lok:prod
  interface: lok
  issuer: lok
  key_type: RS256
  long: This includes authorization, authentificaiton, config management, and more
  name: lok
  port: 8000
  private_key: '-----BEGIN PRIVATE KEY-----

    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgQ4wDZaLBBioN

    RExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HP

    I0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox

    /M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN

    7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetK

    dkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2

    aG+h4K1lAgMBAAECggEAHlk8OeZ0wB3FN9bvqC0LTaplaTEzKrT3JKUX9mlhrhgk

    +E4cWoo1srd+vR9nxSEtEEGIw/fkBKBOhR21oWryw9KJDKARVsLkqbDwyaZBbu+A

    G/F3EMqEu6H468UWb6EIr+b6WNbtt1Vg0+9+Bn+6HqHjcJTOw5F7ZPnJWh9xKFLa

    G3pMyVkq0/NOrN5txc5JXOKPYqvjjTk5i0zk//ONhoYuraUJM8yzJYTjd0PHtYgs

    KreYyKc5J98iCa3AEzzu/zNseAwa1DchM0MyvUiRbNluB0qD+HenouzPyKxrghmu

    Nk3cWnBMijI7D6vEbye/H541FBWXPseua2V+6LayDwKBgQDJX7+U+0gsrQmMNKDw

    HMkrFGGhMBNtb4sR47JbJDrwqlwRxyellBtRJ7zRjw6iAk2mpSc8WzfxsQk8DqM6

    ZsjJ/GBoyZ5ICawVDF6ato79Gny6hzx0KxS/OpIsd6pRzaLjiLmje1TfGyB4FLhh

    oiLs0d6r4OVhVqKZNfXybMdnRwKBgQDLvO/9NLxKaT/nVthRmc7V8RDpJODy627n

    RufnzJ9QCPs7tvd/YhgnefirADZ9xu1hRY2JQjadAVln71AFgBENR8P3f8w7maE6

    ftBgIPDIPEL+qK/S2ZM5HYUP7X8v3h7ppInYX3SsXqj/X1ko7kkFyesCMbeTpVAf

    yJl4GQWz8wKBgARgIDmMfDT8TYjOW/Dbr0NQXg6yjLmEAvGQkP+J+f3gtb9tJF9k

    qHNK+b9T7G14v1cvn3qgQMbvodO8Pa+3LAW3hiDAwL+v9h0+949FCDZXrP4gkh+0

    D+9XxnVQ5FKCtVdcUSxMMbvnSv1Q9fCpJTkgFkaFzHYg+8d4dK+fzXVhAoGBAJiP

    05nkynZiF+Mwqe144mRcDtC2t+fPmo1/EBsIo+d3wkF2AiEWIIY3FJlgIG3Q72Ke

    hZzZwzGQmBV3I5Hq01oBemI0BYg/w3adDYZeRE98qKIvSPH30QG89C34Jvx+NOG6

    PyqSWDjW7W/FQ2ud+3plOCC9f/0EllomiZ1gB2A3AoGAV2bj3IFJybOTtRlqF3eI

    sKgBG5UO+Cs6+MyyXFPQo54Sg5mdhxKaAKTB0meWlyTMczA/o5C+ZcwKRR7tI9c/

    6TRmuKoyW7C6XsnoyeIELzuQjrhGCTwnO3sl3U7l3sp2Bt2exzVxU9uj80cI9knm

    l2hr8PzE2jOOOjWzv3HT4Eg=

    -----END PRIVATE KEY-----

    '
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgQ4wDZaLBBioNRExYbL0L/SJjYE7LvhIfqxvjhS9B7sw+e6KnCLhZIuFpW+JEEf3H94XAAXwjR7HPI0IAPSTt3TgUZzhh3NFiFjnU45ZJeXeT3GBLnM/uJqWn26iDGUPfxcs1wEriSaox/M1JYL8PpXInLVYjgV2mG7WyehSaLYH58mZgnYa8T8wFSEd2gTa/6O2jau2oS3VN7R5qk+GBXUn2Nc+hwnNyxXZf32XtOTWgIdSgdDc8wwgtRAhsX8qqWcY/tlbMxetKdkeOSZYRnLnaEkduLgAsiMkOG26PThYoQ00o4wpLcS918S23oNpo0te8gZyHqxY2aG+h4K1l
  public_port: 8000
  required_buckets:
  - name: lokmedia
  required_policies:
  - readwrite
  requires:
  - redis
  - db
  - minio
  scopes:
    can_assign: Can Assign Nodes
    can_create: Can Create Nodes
    can_create_identifier: Can create new identifier for the platform
    can_forward_bounce: Can reserve and assign to Nodes mimicking other Users (only
      backend and admin)
    can_provide: Can Provide Nodes
    can_template: Can Template Nodes
    introspection: Introspect the Token scope
    provider: Can act as a provider
    read: Reading all of your Data
    read_starred: Reading all of your shared Data
  token_expire_seconds: 604800
- dependencies: {}
  description: The broker
  dev: null
  host: rekuest
  image: jhnnsrs/rekuest:prod
  interface: rekuest
  long: Allows you to call enabled bioimage apps from the platform
  name: rekuest
  port: 8090
  public_port: 8090
  requires:
  - redis
  - rabbitmq
  - lok
  - db
users:
- email: sdfsd@gmail.com
  groups:
  - myteam
  password: sdf
  username: sdf
